title: Radi Akbar
author:
  name: Radi Akbar
  email: kadimasha123@gmail.com
  
# Description of the webstie
description: >
  This is a personal website of Radi Akbar
  
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about_me.md
  - projects.md

minima:
  skin: classic
  date_format: "%b-%d-%Y"
  social_links:
    - {platform: linkedin,       user_url: https://www.linkedin.com/in/radia78/" }
