title: Radi Akbar
theme: jekyll-theme-minimal
description: Hi! I'm a statistical programmer at Acumen LLC, but right now I'm interested in transitioning to machine learning research. In have a general interest in the intersection of NLP and CV. You can contact me by email if you have any inquiries.
